### ISSUE TITLE
Oil node size

### ISSUE THREAD

**Issue by Fanatic191** [DellAquila/ResourceNodeCreator#7]
Oil node too big. MAybe 3-5 times bigger, than any others. 
![image](https://github.com/user-attachments/assets/d3ccd4dd-d3a8-4598-92ce-559387eec30f)

**Comment by BlackHorde22** [comment]
Yeah I was just gonna report this.. I was like, eeeewwww!

**Comment by Fanatic191** [comment]
![image](https://github.com/user-attachments/assets/b1f0ac41-8cd7-48f5-9435-6096d2d1c7d6)
I think, all the other nodes are too big.

**Comment by Fanatic191** [comment]
![image](https://github.com/user-attachments/assets/23611e2f-1ef2-4214-86d5-cb7220a86f8c)
At placing, no problem, spawning... 3 times bigger.

**Comment by BlackHorde22** [comment]
Not to mention out of place, when you put the iron one down it's half way off the ground, could use a Nugg' ?

**Comment by BlackHorde22** [comment]
Thank You for the Update!

**Comment by Fanatic191** [comment]
Update working fine, spawn locations also good, same spot as i add. I'll close the theard, solved. Thanks. :)
